//
// AppEventAssetType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum AppEventAssetType: String, Codable, CaseIterable {
    case card = "EVENT_CARD"
    case detailsPage = "EVENT_DETAILS_PAGE"
}
