//
// BundleIdPlatform.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum BundleIdPlatform: String, Codable, CaseIterable {
    case ios = "IOS"
    case macOs = "MAC_OS"
}
