//
// ActorsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ActorsAPI {

    /**
     * enum for parameter fieldsActors
     */
    public enum FieldsActors_actorsGetCollection: String, CaseIterable {
        case actortype = "actorType"
        case apikeyid = "apiKeyId"
        case useremail = "userEmail"
        case userfirstname = "userFirstName"
        case userlastname = "userLastName"
    }

    /**

     - parameter filterId: (query) filter by id(s) 
     - parameter fieldsActors: (query) the fields to include for returned resources of type actors (optional)
     - parameter limit: (query) maximum resources per page (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func actorsGetCollection(filterId: [String], fieldsActors: [FieldsActors_actorsGetCollection]? = nil, limit: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ActorsResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return actorsGetCollectionWithRequestBuilder(filterId: filterId, fieldsActors: fieldsActors, limit: limit).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /v1/actors
     - Bearer Token:
       - type: http
       - name: itc-bearer-token
     - parameter filterId: (query) filter by id(s) 
     - parameter fieldsActors: (query) the fields to include for returned resources of type actors (optional)
     - parameter limit: (query) maximum resources per page (optional)
     - returns: RequestBuilder<ActorsResponse> 
     */
    open class func actorsGetCollectionWithRequestBuilder(filterId: [String], fieldsActors: [FieldsActors_actorsGetCollection]? = nil, limit: Int? = nil) -> RequestBuilder<ActorsResponse> {
        let localVariablePath = "/v1/actors"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "filter[id]": (wrappedValue: filterId.encodeToJSON(), isExplode: false),
            "fields[actors]": (wrappedValue: fieldsActors?.encodeToJSON(), isExplode: false),
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ActorsResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     * enum for parameter fieldsActors
     */
    public enum FieldsActors_actorsGetInstance: String, CaseIterable {
        case actortype = "actorType"
        case apikeyid = "apiKeyId"
        case useremail = "userEmail"
        case userfirstname = "userFirstName"
        case userlastname = "userLastName"
    }

    /**

     - parameter id: (path) the id of the requested resource 
     - parameter fieldsActors: (query) the fields to include for returned resources of type actors (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func actorsGetInstance(id: String, fieldsActors: [FieldsActors_actorsGetInstance]? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: ActorResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return actorsGetInstanceWithRequestBuilder(id: id, fieldsActors: fieldsActors).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /v1/actors/{id}
     - Bearer Token:
       - type: http
       - name: itc-bearer-token
     - parameter id: (path) the id of the requested resource 
     - parameter fieldsActors: (query) the fields to include for returned resources of type actors (optional)
     - returns: RequestBuilder<ActorResponse> 
     */
    open class func actorsGetInstanceWithRequestBuilder(id: String, fieldsActors: [FieldsActors_actorsGetInstance]? = nil) -> RequestBuilder<ActorResponse> {
        var localVariablePath = "/v1/actors/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "fields[actors]": (wrappedValue: fieldsActors?.encodeToJSON(), isExplode: false),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ActorResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
