//
// GameCenterMatchmakingRuleSetTestsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class GameCenterMatchmakingRuleSetTestsAPI {

    /**

     - parameter gameCenterMatchmakingRuleSetTestCreateRequest: (body) GameCenterMatchmakingRuleSetTest representation 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func gameCenterMatchmakingRuleSetTestsCreateInstance(gameCenterMatchmakingRuleSetTestCreateRequest: GameCenterMatchmakingRuleSetTestCreateRequest, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: GameCenterMatchmakingRuleSetTestResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return gameCenterMatchmakingRuleSetTestsCreateInstanceWithRequestBuilder(gameCenterMatchmakingRuleSetTestCreateRequest: gameCenterMatchmakingRuleSetTestCreateRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /v1/gameCenterMatchmakingRuleSetTests
     - Bearer Token:
       - type: http
       - name: itc-bearer-token
     - parameter gameCenterMatchmakingRuleSetTestCreateRequest: (body) GameCenterMatchmakingRuleSetTest representation 
     - returns: RequestBuilder<GameCenterMatchmakingRuleSetTestResponse> 
     */
    open class func gameCenterMatchmakingRuleSetTestsCreateInstanceWithRequestBuilder(gameCenterMatchmakingRuleSetTestCreateRequest: GameCenterMatchmakingRuleSetTestCreateRequest) -> RequestBuilder<GameCenterMatchmakingRuleSetTestResponse> {
        let localVariablePath = "/v1/gameCenterMatchmakingRuleSetTests"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: gameCenterMatchmakingRuleSetTestCreateRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GameCenterMatchmakingRuleSetTestResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
