//
// SandboxTestersClearPurchaseHistoryRequestAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class SandboxTestersClearPurchaseHistoryRequestAPI {

    /**

     - parameter sandboxTestersClearPurchaseHistoryRequestV2CreateRequest: (body) SandboxTestersClearPurchaseHistoryRequest representation 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func sandboxTestersClearPurchaseHistoryRequestV2CreateInstance(sandboxTestersClearPurchaseHistoryRequestV2CreateRequest: SandboxTestersClearPurchaseHistoryRequestV2CreateRequest, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: SandboxTestersClearPurchaseHistoryRequestV2Response?, _ error: Error?) -> Void)) -> RequestTask {
        return sandboxTestersClearPurchaseHistoryRequestV2CreateInstanceWithRequestBuilder(sandboxTestersClearPurchaseHistoryRequestV2CreateRequest: sandboxTestersClearPurchaseHistoryRequestV2CreateRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /v2/sandboxTestersClearPurchaseHistoryRequest
     - Bearer Token:
       - type: http
       - name: itc-bearer-token
     - parameter sandboxTestersClearPurchaseHistoryRequestV2CreateRequest: (body) SandboxTestersClearPurchaseHistoryRequest representation 
     - returns: RequestBuilder<SandboxTestersClearPurchaseHistoryRequestV2Response> 
     */
    open class func sandboxTestersClearPurchaseHistoryRequestV2CreateInstanceWithRequestBuilder(sandboxTestersClearPurchaseHistoryRequestV2CreateRequest: SandboxTestersClearPurchaseHistoryRequestV2CreateRequest) -> RequestBuilder<SandboxTestersClearPurchaseHistoryRequestV2Response> {
        let localVariablePath = "/v2/sandboxTestersClearPurchaseHistoryRequest"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sandboxTestersClearPurchaseHistoryRequestV2CreateRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SandboxTestersClearPurchaseHistoryRequestV2Response>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
